# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bin/bridgetown start`. If you change this file, please restart the server process.

url: "" # the base hostname & protocol for your site, e.g. https://example.com

permalink: pretty
template_engine: erb

timezone: America/New_York

learn_ruby_repo:
  local_path: "/home/felipe/code/learn-ruby"
  github_url: "https://raw.githubusercontent.com/fpsvogel/learn-ruby/main/README.md"

title: Let's Learn Ruby
subtitle: a resource list
callout: "If you like this list, please star it at [github.com/fpsvogel/learn-ruby](https://github.com/fpsvogel/learn-ruby). This page is generated automatically from the \"done\" and bullet-point items in that repo."
