# Re-build and deploy weekly to sync to github.com/fpsvogel/learn-ruby
name: Deploy to Render
on:
  schedule:
    # Every Tuesday at midnight. See https://crontab.guru
    - cron: '0 0 * * TUE'
jobs:
  post_to_netlify_deploy_hook:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK_URL }}
